### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by ioquatix** [Freaky/monotime#1]
You might like to add this link as an alternative. Not sure if you are aware of it.

https://github.com/copiousfreetime/hitimes

**Comment by Freaky** [comment]
I'll consider that when I finish reworking the README.

I might move the pure-Ruby example into such a section and mention hitimes there, so people see both an alternative library they might use, and also how to avoid using one all together.

**Comment by ioquatix** [comment]
I like having a See Also section. Maybe that works for you too :)

**Comment by Freaky** [comment]
Fixed (finally!) in 0.7.0.  Thanks for the suggestion :)

**Comment by ioquatix** [comment]
Awesome!
